Skip app check for ringtools
runcitadel/dashboard pull request #32
Opened 2022-06-06 07:08 UTC by AaronDewes

Even with the CORS fix, the app was still shown as "starting". So this will work as a temporary workaround for 0.0.5

2022-06-07 14:14 UTC, pwltr commented
The same logic should be added to `AppStoreApp.vue` that also contains the polling. A fallback idea to work around this CORS issue would be to work with the manager to check for container status with something like `docker container inspect -f '{{.State.Status}}' ringtools-main-1`. It's not as good an end-to-end as the current HTTP request polling but it would work around the CORS/CORP issues. It also might come in handy for apps that don't have a web UI.

2022-06-07 14:16 UTC, pwltr commented
We should also add some screenshots for this app.

2022-06-07 14:37 UTC, AaronDewes commented
Sure, they can be added later. Will update the AppStoreApp code though.

2022-07-04 18:17 UTC, pwltr requested changes

2022-07-04 18:17 UTC, pwltr commented on src/components/InstalledApp.vue
> +      if (skipCheckApps.includes(this.id)) this.checkIfAppIsOffline = false;
Add the same logic to `AppStoreApp.vue`

2022-07-08 17:59 UTC, pwltr approved these changes

2022-07-09 02:24 UTC, WilliamConnatser approved these changes

2022-07-09 02:25 UTC, merged